[package]
name = "lgn-graphics-cgen"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-graphics-api = { path = "../lgn-graphics-api", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-telemetry-sink = { path = "../lgn-telemetry-sink", version = "0.1.0" }
lgn-utils = { path = "../lgn-utils", version = "0.1.0" }
lgn-build-utils = { path = "../lgn-build-utils", version = "0.1.0" }

anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
fxhash = "0.2"
hassle-rs = { git = "https://github.com/legion-labs/hassle-rs", rev = "957746c04479e7df7eb37c70ea733fc18aefcbc5" }
heck = "0.4"
petgraph = "0.6.0"
relative-path = "1.6"
rune = "0.10.3"
serde = "1.0"
serde_json = "1.0"
spirv-reflect = "0.2"
strum = { version = "0.23", features = ["derive"] }
