[package]
name = "lgn-graphics-renderer"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-app = { path = "../lgn-app", version = "0.1.0" }
lgn-asset-registry = { path = "../lgn-asset-registry", version = "0.1.0" }
lgn-core = { path = "../lgn-core", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-data-model = { path = "../lgn-data-model", version = "0.1.0" }
lgn-ecs = { path = "../lgn-ecs", version = "0.1.0" }
lgn-graphics-api = { path = "../lgn-graphics-api", version = "0.1.0", features = [
    "track-device-contexts",
] }
lgn-graphics-cgen-runtime = { path = "../lgn-graphics-cgen-runtime", version = "0.1.0" }
lgn-graphics-data = { path = "../lgn-graphics-data", version = "0.1.0" }
lgn-hierarchy = { path = "../lgn-hierarchy", version = "0.1.0" }
lgn-input = { path = "../lgn-input", version = "0.1.0" }
lgn-math = { path = "../lgn-math", version = "0.1.0" }
lgn-pso-compiler = { path = "../lgn-pso-compiler", version = "0.1.0" }
lgn-tasks = { path = "../lgn-tasks", version = "0.1.0" }
lgn-transform = { path = "../lgn-transform", version = "0.1.0" }
lgn-utils = { path = "../lgn-utils", version = "0.1.0" }
lgn-window = { path = "../lgn-window", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-embedded-fs = { path = "../lgn-embedded-fs", version = "0.1.0" }

anyhow = "1.0"
async-trait = "0.1"
atomic_refcell = "0.1"
bitflags = "1.3"
bit-set = "0.5"
bumpalo = { version = "3.9.1", features = ["collections"] }
bumpalo-herd = "0.1"
crossbeam = "0.8"
crossbeam-channel = "0.5"
egui = "0.18.1"
parking_lot = "0.12"
paste = "1.0.6"
renderdoc = "0.10.1"
slab = "0.4.4"
slotmap = "1.0.6"
smallvec = "1.7"
static_assertions = "1.1.0"
strum = { version = "0.23" }
thiserror = "1.0.30"
tokio = { version = "1", features = ["full", "tracing"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

[build-dependencies]
lgn-graphics-cgen = { path = "../lgn-graphics-cgen", version = "0.1.0" }

[features]
default = ["lgn-graphics-api/vulkan", "bumpalo/collections"]
vulkan = ["lgn-graphics-api/vulkan"]
