[package]
name = "lgn-pso-compiler"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-graphics-api = { path = "../lgn-graphics-api", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
hassle-rs = { git = "https://github.com/legion-labs/hassle-rs", branch = "com_to_tinycom" }
normpath = "0.3"
spirv-reflect = "0.2"
spirv-tools = "0.7"
anyhow = "1"
