[package]
name = "lgn-graphics-data"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-data-offline = { path = "../lgn-data-offline", version = "0.1.0", optional = true }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-math = { path = "../lgn-math", version = "0.1.0" }
lgn-app = { path = "../../crates/lgn-app", version = "0.1.0" }
lgn-ecs = { path = "../../crates/lgn-ecs", version = "0.1.0" }
lgn-data-model = { path = "../../crates/lgn-data-model", version = "0.1.0" }

ispc-tex = "0.1.0"
tbc = "0.3.0"

# offline
gltf = { version = "1.0.0", optional = true }
inventory = { version = "0.2", optional = true }
psd = { version = "0.3.0", optional = true }

# codegen
bincode = "1.3.3"
erased-serde = "0.3.12"
lazy_static = "1.4"
memoffset = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
typetag = "0.1.8"
async-trait = "0.1"
tokio = { version = "1.13" }

[build-dependencies]
lgn-data-codegen = { path = "../../crates/lgn-data-codegen", version = "0.1.0" }

[features]
default = ["runtime"]
offline = ["lgn-data-offline", "gltf", "inventory", "psd"]
runtime = []
