[package]
name = "lgn-data-build-cli"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "data-build"
path = "src/data-build/main.rs"
doc = false

[[bin]]
name = "data-scrape"
path = "src/scrape/main.rs"

[dependencies]
byteorder = "1.4"
clap = { version = "3.0", features = ["derive"] }
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
lgn-data-build = { path = "../lgn-data-build", version = "0.1.0" }
lgn-data-compiler = { path = "../lgn-data-compiler", version = "0.1.0" }
lgn-content-store = { path = "../lgn-content-store", version = "0.1.0" }
lgn-data-offline = { path = "../lgn-data-offline", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }

[dev-dependencies]
tempfile = "3.2.0"
refs-resource = { path = "../lgn-data-offline/test-refs-resource", version = "0.1.0" }
text-resource = { path = "../lgn-data-offline/test-text-resource", version = "0.1.0" }
integer-asset = { path = "../lgn-data-runtime/test-integer-asset", version = "0.1.0" }
refs-asset = { path = "../lgn-data-runtime/test-refs-asset", version = "0.1.0" }
