[package]
name = "lgn-web-client"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.44"
directories = "4"
lgn-online = { path = "../lgn-online", version = "0.1.0" }
serde_json = "1.0"
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
url = "2.2.2"
