[package]
name = "aws-lambda-grpc-test"
version = "0.1.0"
edition = "2021"
description = "Legion AWS Lambda that tests gRPC"
authors = ["devs@legionlabs.com"]
repository = ""
license = "MIT OR Apache-2.0"
keywords = ["game", "legion"]

[dependencies]
legion-aws = { path = "../../lib/aws", version = "0.1.0" }
legion-online = { path = "../../lib/online", version = "0.1.0" }
tokio = { version = "1.13", features = ["full"] }
tonic = "0.6"
tonic-web = "0.2"
hyper = "0.14"
anyhow = "1.0"
lambda_runtime = "0.4"
lambda_http = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simple_logger = "1.13"
legion-streaming-proto = { path = "../../proto/streaming", version = "0.1.0" }
http = "0.2"
http-body = "0.4.4"
bytes = "1.1"
