[package]
name = "lgn-asset-registry"
version = "0.1.0"
edition = "2021"
description = "Provides access to the runtime asset-registry for Legion Engine"
homepage = "https://legionengine.com"
repository = "https://github.com/legion-labs/legion"
license = "MIT OR Apache-2.0"
keywords = ["legion"]

[dependencies]
# Legion engine
lgn-app = { path = "../lgn-app", version = "0.1.0" }
lgn-content-store = { path = "../lgn-content-store", version = "0.1.0" }
lgn-core = { path = "../lgn-core", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-data-model = { path = "../lgn-data-model", version = "0.1.0" }
lgn-config = { path = "../lgn-config", version = "0.1.0" }
lgn-ecs = { path = "../lgn-ecs", version = "0.1.0" }
lgn-graphics-data = { path = "../lgn-graphics-data", version = "0.1.0", features = [
    "runtime",
] }
lgn-transform = { path = "../lgn-transform", version = "0.1.0" }
lgn-renderer = { path = "../lgn-renderer", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-scripting = { path = "../lgn-scripting", version = "0.1.0", features = [
    "runtime",
] }

# temp dependency on sample-data, until runtime data moved to plugins
sample-data = { path = "../../tests/sample-data", version = "0.1.0", features = [
    "runtime",
] }

# other
crossbeam-channel = "0.5.1"
serde_json = "1.0"
