[package]
name = "lgn-runtime-proto"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.13", features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }
base64 = "0.13.0"

[build-dependencies]
tonic-build = "0.6"
