[package]
name = "lgn-source-control"
version = "0.1.0"
authors = ["mad-legion <mad@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
async-trait = "0.1"
async-recursion = "1"
aws-config = "0.6"
aws-sdk-s3 = "0.6"
bytes = "1"
chrono = "0.4"
dirs = "4.0"
futures = "0.3"
glob = "0.3"
http = "0.2"
itertools = "0.10"
lgn-blob-storage = { path = "../lgn-blob-storage", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-source-control-proto = { path = "../lgn-source-control-proto", version = "0.1.0" }
lgn-online = { path = "../lgn-online", version = "0.1.0" }
lz4 = "1.23"
path-clean = "0.1"
path-slash = "0.1"
pin-project = "1"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sqlx = { version = "0.5", features = [
    "sqlite",
    "any",
    "mysql",
    "runtime-tokio-native-tls",
] }
tempfile = "3.2"
thiserror = "1"
tokio = { version = "1.13", features = ["full", "tracing"] }
tokio-util = { version = "0.6.9", features = ["full"] }
tokio-stream = "0.1.8"
pathdiff = "0.2"
url = "2.2"
urlencoding = "1.3.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
whoami = "1.2"
