[package]
name = "lgn-content-store"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-utils = { path = "../lgn-utils" }
hex = "0.4.3"
hex_fmt = "0.3.0"
serde = "1.0"
