[package]
name = "lgn-transform"
version = "0.1.0"
edition = "2021"
description = "Provides hierarchy and transform functionality for Legion Engine"
homepage = "https://legionengine.com"
repository = "https://github.com/legion-labs/legion"
license = "MIT OR Apache-2.0"
keywords = ["legion"]

[dependencies]
# legion
lgn-app = { path = "../lgn-app", version = "0.1.0" }
lgn-ecs = { path = "../lgn-ecs", version = "0.1.0" }
lgn-math = { path = "../lgn-math", version = "0.1.0" }
lgn-utils = { path = "../lgn-utils", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }

# other
smallvec = { version = "1.7", features = ["serde", "union", "const_generics"] }
