[package]
name = "legion-data-build"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion-resources = { path = "../resources" }
legion-data-compiler = { path = "../data-compiler" }
legion-asset-store = { path = "../asset-store" }
legion-assets = { path = "../assets" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
petgraph = "0.6.0"
byteorder = "1"

[dev-dependencies]
tempfile = "3.2.0"
