[package]
name = "lgn-auth"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["aws", "ttl"]
aws = ["aws-config", "aws-sdk-s3", "aws-sdk-dynamodb"]
ttl = ["ttl_cache"]

[dependencies]
aws-config = { version = "0.12", optional = true }
aws-sdk-s3 = { version = "0.12", optional = true }
aws-sdk-dynamodb = { version = "0.12", optional = true }
async-trait = "0.1.53"
base64 = "0.13.0"
form_urlencoded = "1.0.1"
futures-util = "0.3.21"
http-body = "0.4.4"
http = "0.2.6"
http-serde = "1.1.0"
lgn-config = { path = "../lgn-config", version = "0.1.0" }
lgn-tracing = { path = "../../crates/lgn-tracing", version = "0.1.0" }
ttl_cache = { version = "0.5", optional = true }
# napi = { version = "2.4.3", features = [
#     "tokio_rt",
#     "serde-json",
# ], optional = true }
# napi-derive = { version = "2.4.1", optional = true }
openidconnect = "2.3.1"
reqwest = "0.11.10"
ring = "0.16.20"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
simple_asn1 = "0.6.1"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full", "tracing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories = "4.0.1"
hyper = { version = "0.14.18", features = ["full"] }
hyper-rustls = { version = "0.23", features = ["http2"] }
tower-http = { version = "0.3.1", features = ["full"] }
webbrowser = "0.7.1"

[build-dependencies]
napi-build = { version = "2.0.0", optional = true }

# TODO: Expose a Node feature
# [features]
# node = ["dep:napi", "dep:napi-derive", "dep:napi-build"]
