[package]
name = "lgn-config"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "1"
figment = { version = "0.10", features = ["toml", "env", "test"] }
lazy_static = "1.4"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1"
toml = "0.5.8"
