[package]
name = "lgn-online"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["grpc"]
grpc = ["tonic", "tonic-web"]

# TODO: Drop unused deps

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.5"
base64 = "0.13"
bytes = "1.1"
directories = "4"
dyn-clone = "1"
http = "0.2"
http-body = "0.4"
http-serde = "1.1"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.23", features = ["http2"] }
lgn-auth = { path = "../lgn-auth", version = "0.1.0" }
lgn-config = { path = "../lgn-config", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
openidconnect = "2.2.0"
percent-encoding = "2"
pin-project = "1"
reqwest = "0.11"
ring = "0.16"
rustls = "= 0.20.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_asn1 = "0.6"
thiserror = "1"
tokio = { version = "1.13", features = ["full", "tracing"] }
tonic = { version = "0.6", features = ["tls-roots"], optional = true }
tonic-web = { version = "0.2", optional = true }
tower = "0.4.8"
tower-http = { version = "0.3", features = ["full"] }
tower-service = "0.3.1"
url = "2.2"
webbrowser = "0.7.1"

[build-dependencies]
tonic-build = "0.6"

[dev-dependencies]
prost = "0.9"
serial_test = "0.6"
backoff = { version = "0.4.0", features = ["tokio"] }
