[package]
name = "lgn-online"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
aws = ["lambda_runtime", "lambda_http", "strum", "strum_macros"]

[dependencies]
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-config = { path = "../lgn-config", version = "0.1.0" }
anyhow = "1"
thiserror = "1"
tokio = { version = "1.13", features = ["full", "tracing"] }
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.23", features = ["http2"] }
tower = "0.4.8"
tower-http = { version = "0.2", features = ["full"] }
tower-service = "0.3.1"
tonic = { version = "0.6", features = ["tls-roots"] }
tonic-web = "0.2"
rustls = "0.20"
webbrowser = "0.6"
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
directories = "4"
reqwest = "0.11"
ring = "0.16"
simple_asn1 = "0.6"
async-trait = "0.1"
bytes = "1.1"
http = "0.2"
http-body = "0.4"
pin-project = "1"
dyn-clone = "1"
lambda_runtime = { version = "0.5.0", optional = true }
lambda_http = { version = "0.5.0", optional = true }
strum = { version = "0.23", optional = true }
strum_macros = { version = "0.23", optional = true }
openidconnect = "2.2.0"

[build-dependencies]
tonic-build = "0.6"

[dev-dependencies]
prost = "0.9"
serial_test = "0.5"
backoff = { version = "0.4.0", features = ["tokio"] }
