[package]
name = "lgn-scripting"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Legion engine
lgn-app = { path = "../lgn-app", version = "0.1.0" }
lgn-core = { path = "../lgn-core", version = "0.1.0" }
lgn-data-model = { path = "../lgn-data-model", version = "0.1.0" }
lgn-data-offline = { path = "../lgn-data-offline", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-ecs = { path = "../lgn-ecs", version = "0.1.0" }
lgn-input = { path = "../lgn-input", version = "0.1.0" }
lgn-math = { path = "../lgn-math", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-transform = { path = "../lgn-transform", version = "0.1.0" }

# other
bincode = "1.3"
erased-serde = "0.3.12"
lazy_static = "1.4"
memoffset = "0.6"
mun_runtime = "0.3.0"
rand = "0.8"
rune = "0.10.3"
rune-modules = "0.10.3"
rhai = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typetag = "0.1"
inventory = "0.2"

[build-dependencies]
lgn-data-codegen = { path = "../lgn-data-codegen", version = "0.1.0" }

[features]
default = ["runtime"]
offline = []
runtime = []

[package.metadata.cargo-udeps.ignore]
normal = [
    "lgn-input",
    "lgn-transform",
    "mun_runtime",
    "rhai",
    "rune",
    "rune-modules",
]
