[package]
name = "runtime-srv"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
# Legion engine
legion-app = { path = "../../lib/app", version = "0.1.0" }
legion-asset-registry = { path = "../../plugin/asset-registry", version = "0.1.0" }
legion-core = { path = "../../plugin/core", version = "0.1.0" }
legion-transform = { path = "../../plugin/transform", version = "0.1.0" }
legion-utils = { path = "../../lib/utils", version = "0.1.0" }

# other
clap = "2.33"
