[package]
name = "runtime-srv"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Legion engine
legion-app = { path = "../../core/app", version = "0.1.0" }
legion-core = { path = "../../core/core", version = "0.1.0" }
legion-ecs = { path = "../../core/ecs", version = "0.1.0" }
legion-transform = { path = "../../core/transform", version = "0.1.0" }
legion-utils = { path = "../../core/utils", version = "0.1.0" }

# other
