[package]
name = "runtime-srv"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Legion engine
lgn-app = { path = "../../lib/app", version = "0.1.0" }
lgn-asset-registry = { path = "../../plugin/asset-registry", version = "0.1.0" }
lgn-async = { path = "../../plugin/async", version = "0.1.0" }
lgn-core = { path = "../../plugin/core", version = "0.1.0" }
lgn-data-runtime = { path = "../../lib/data-runtime", version = "0.1.0" }
lgn-ecs = { path = "../../lib/ecs", version = "0.1.0" }
lgn-grpc = { path = "../../plugin/grpc", version = "0.1.0" }
lgn-input = { path = "../../plugin/input" }
lgn-presenter-window = { path = "../../plugin/presenter-window", version = "0.1.0" }
lgn-renderer = { path = "../../plugin/renderer", version = "0.1.0" }
lgn-streamer = { path = "../../plugin/streamer", version = "0.1.0" }
lgn-telemetry = { path = "../../lib/telemetry", version = "0.1.0" }
lgn-transform = { path = "../../plugin/transform", version = "0.1.0" }
lgn-utils = { path = "../../lib/utils", version = "0.1.0" }
lgn-config = { path = "../../lib/config", version = "0.1.0" }
lgn-winit = { path = "../../plugin/winit", version = "0.1.0" }
lgn-window = { path = "../../plugin/window", version = "0.1.0" }
lgn-telemetry-sink = { path = "../../lib/telemetry-sink", version = "0.1.0" }

# other
clap = { version = "3.0", features = ["derive"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }

[features]
default = ["standalone"]
standalone = []
