[package]
name = "source-control-srv"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion-source-control = { path = "../../lib/source-control" }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
bytes = "1.0"
http = { version = "0.2.4" }
hyper = "0.14"
futures = "0.3"
lazy_static = "1.4"
serde_json = "1.0"
