[package]
name = "lgn-graphics-runtime"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
byteorder = "1.4"
