[package]
name = "lgn-content-store2"
description = "Content-Access Storage interface and utilities to store assets at scale."
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "lgn_content_store2"
path = "src/lib.rs"

[[bin]]
name = "lgn-content-store-cli"
path = "src/bin.rs"
required-features = ["cli"]

[[bin]]
name = "lgn-content-store-srv"
path = "src/server.rs"
required-features = ["server"]

[features]
default = ["aws", "redis", "lru", "cli", "server"]
aws = ["aws-config", "aws-sdk-s3", "aws-sdk-dynamodb"]
cli = ["clap", "indicatif", "bytesize"]
server = [
    "clap",
    "tonic-web",
    "tower",
    "tower-http",
    "bytesize",
    "lgn-cli-utils",
    "lgn-tracing",
    "lgn-telemetry-sink",
]

[dependencies]
anyhow = "1.0"
aws-config = { version = "0.8", optional = true }
aws-sdk-s3 = { version = "0.8", optional = true }
aws-sdk-dynamodb = { version = "0.8", optional = true }
async-trait = "0.1"
base64 = "0.13"
blake3 = { version = "1.3", features = ["prefer_intrinsics"] }
bytesize = { version = "1", optional = true }
byteorder = "1.4.3"
bytes = "1.1.0"
clap = { version = "3.0", features = ["derive"], optional = true }
futures = "0.3"
http = "0.2.6"
http-body = "0.4"
indicatif = { version = "0.16", optional = true }
itertools = "0.10"
lgn-online = { path = "../lgn-online", version = "0.1.0" }
lgn-config = { path = "../lgn-config", version = "0.1.0" }
lgn-content-store-proto = { path = "../lgn-content-store-proto", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0", optional = true }
lgn-telemetry-sink = { path = "../lgn-telemetry-sink", version = "0.1.0", optional = true }
lgn-cli-utils = { path = "../lgn-cli-utils", version = "0.1.0", optional = true }
lru = { version = "0.7", optional = true }
pin-project = "1"
redis = { version = "0.21.0", features = ["tokio-comp"], optional = true }
reqwest = { version = "0.11.9", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.8.0"
tempfile = "3.2"
thiserror = "1.0"
tonic = "0.6"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.6.9", features = ["full"] }
toml = "0.5"
tonic-web = { version = "0.2", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.2", features = ["cors"], optional = true }

[dev-dependencies]
rmp-serde = "1"
uuid = { version = "0.8", features = ["v4"] }
hex = "0.4"
httptest = "0.15"
hyper = "0.14"
pretty_env_logger = "0.4"
rand = "0.8"
testcontainers = "0.12"

[[package.metadata.monorepo.publish]]
name = "content-store-srv"
type = "docker"
target-bin-dir = "/usr/src/app"
template = """
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y libssl-dev ca-certificates

{ copy_all }

ENTRYPOINT ["{ binaries.lgn-content-store-srv }"]
"""
allow-aws-ecr-creation = true
