[package]
name = "lgn-content-store2"
description = "Content-Access Storage interface and utilities to store assets at scale."
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "lgn_content_store2"
path = "src/lib.rs"

[[bin]]
name = "lgn-content-store-cli"
path = "src/bin.rs"
required-features = ["cli"]

[features]
default = ["aws", "redis", "cli"]
aws = ["aws-config", "aws-sdk-s3", "aws-sdk-dynamodb"]
cli = ["clap", "indicatif"]

[dependencies]
anyhow = "1.0"
aws-config = { version = "0.6", optional = true }
aws-sdk-s3 = { version = "0.6", optional = true }
aws-sdk-dynamodb = { version = "0.6", optional = true }
async-trait = "0.1"
base64 = "0.13"
blake3 = "1.3"
byteorder = "1.4.3"
bytes = "1.1.0"
clap = { version = "3.0", features = ["derive"], optional = true }
futures = "0.3"
http = "0.2.6"
http-body = "0.4"
indicatif = { version = "0.16", optional = true }
lgn-online = { path = "../lgn-online", version = "0.1.0" }
lgn-config = { path = "../lgn-config", version = "0.1.0" }
lgn-content-store-proto = { path = "../lgn-content-store-proto", version = "0.1.0" }
pin-project = "1"
redis = { version = "0.21.0", features = ["tokio-comp"], optional = true }
reqwest = { version = "0.11.9", features = ["stream"] }
smallvec = "1.8.0"
tempfile = "3.2"
thiserror = "1.0"
tonic = "0.6"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.6.9", features = ["full"] }

[dev-dependencies]
uuid = { version = "0.8", features = ["v4"] }
hex = "0.4"
httptest = "0.15"
hyper = "0.14"
pretty_env_logger = "0.4"
testcontainers = "0.12"
