[package]
name = "lgn-web-client-config"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
lgn-config = { path = "../lgn-config", version = "0.1.0" }
napi = { version = "2.2.0", features = ["serde-json"] }
napi-derive = "2.2.0"
serde = "1.0.136"
serde_json = "1.0.79"

[build-dependencies]
napi-build = "1.2.1"
