[package]
name = "lgn-ecs-macros"
version = "0.1.0"
description = "Legion ECS Macros"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
lgn-macro-utils = { path = "../../lgn-macro-utils", version = "0.1.0" }

syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
