[package]
name = "lgn-async"
version = "0.1.0"
edition = "2021"
description = "Legion's ECS Async plugin"
homepage = "https://legionengine.com"
repository = "https://github.com/legion-labs/legion"
license = "MIT OR Apache-2.0"
keywords = ["ecs", "game", "legion"]

[dependencies]
lgn-ecs = { path = "../lgn-ecs", version = "0.1.0" }
lgn-app = { path = "../lgn-app", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-tasks = { path = "../lgn-tasks", version = "0.1.0" }
tokio = { version = "1.13", features = ["full"] }
retain_mut = "0.1"
futures-lite = "1.12"

[dev-dependencies]
ntest = "0.7"
