[package]
name = "lgn-tasks"
version = "0.1.0"
edition = "2021"
description = "A task executor for the Legion Engine"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
futures-lite = "1.12"
event-listener = "2.5"
async-channel = "1.6"
num_cpus = "1.13"
async-task = "4.0.0"
concurrent-queue = "1.2.2"
fastrand = "1.3.4"
once_cell = "1.4.1"
slab = "0.4.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[dev-dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] }
