[package]
name = "telemetry-ingestion-srv"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
tonic = "0.5.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
telemetry = { path = "../../lib/telemetry" }
uuid = { version = "0.8", features = ["v4"] }
whoami = "1.1"
anyhow = "1.0"
sqlx = { version = "0.5", features = [
    "sqlite",
    "any",
    "mysql",
    "runtime-tokio-native-tls",
] }


[[bin]]
name = "telemetry-ingestion-srv"
path = "src/main.rs"

[[bin]]
name = "telemetry-generator"
path = "test/generator.rs"
