[package]
name = "legion-src-ctl"
version = "0.1.0"
authors = ["mad-legion <mad@legionlabs.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
whoami = "1.1"
path-clean = "0.1"
sha2 = "0.9"
lz4 = "1.23"
chrono = "0.4"
diffy = "0.2"
dirs = "3.0"
glob = "0.3"
git2 = { version = "0.13", features = ["vendored-openssl"] }
unicase = "2.6"
futures = "0.3"
sqlx = { version = "0.5", features = [
    "sqlite",
    "any",
    "mysql",
    "runtime-async-std-native-tls",
] }
tokio = { version = "1", features = ["full"] }
s3 = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.11-alpha", package = "aws-sdk-s3" }
