name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Running code checks
    runs-on: [self-hosted, ubuntu]
    if: {{ false }}
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Run formatting check
        run: make check-format

      - name: Run build checks
        run: make check-build

      - name: Run clippy checks
        run: make check-clippy

      - name: Run dockerize checks
        run: make check-dockerize

      - name: Run dependencies checks
        run: make check-deps

  test:
    name: Running tests
    needs: lint
    strategy:
      matrix:
        include:
          - os: [self-hosted, windows, c5.4xlarge]
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: [self-hosted, ubuntu]
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tests
        run: >-
          docker run
          --name cargo_build
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          make test-build

      - name: Run tests
        run: >-
          docker run
          --name cargo_test
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          make test-run

  bench:
    name: Running benchmarks
    needs: lint
    strategy:
      matrix:
        include:
          - os: [self-hosted, windows, c5.4xlarge]
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: [self-hosted, ubuntu]
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build benchmarks
        run: >-
          docker run
          --name cargo_build
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          make bench-build

      - name: Run benchmarks
        run: >-
          docker run
          --name cargo_bench
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          make bench-run

  coverage:
    name: Running code coverage analysis
    needs: lint
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and run tests
        run: make cov

      - name: Build coverage report
        run: make grcov

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./target/debug/coverage
          retention-days: 60

  build_docs:
    name: Building docs
    #needs: lint
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        run: make api-doc

      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: ./target/doc
          retention-days: 5

  deploy_docs:
    name: Deploying docs
    needs: [build_docs]
    runs-on: [self-hosted, ubuntu]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: doc
          path: ./target/doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          external_repository: legion-labs/api.legionengine.com
          publish_branch: main
          publish_dir: ./target/doc
          force_orphan: true
          cname: api.legionengine.com

  build_release:
    name: Building release binaries
    needs: lint
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build release
        run: make build-release

      - name: Upload release artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./target/release
            !./target/release/build
            !./target/release/deps
            !./target/release/incremental
          retention-days: 5

  dockerize:
    name: Building docker images and deploying them
    needs: [test, build_docs, build_release]
    runs-on: [self-hosted, ubuntu]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: release
          path: ./target

      - name: Docker build
        run: make dockerize-release

      - name: Docker push
        run: make dockerize-push
