name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  base_ref_selection:
    name: Base ref selection
    uses: ./.github/workflows/reusable_base_ref_selection.yml
    with:
      caller_event_name: ${{ github.event_name }}

  image_setup:
    name: Image Setup
    uses: ./.github/workflows/reusable_build_env_setup.yml
    secrets:
      github-token: ${{ secrets.ECR_GH_ACCESS_TOKEN }}

  change_detection:
    name: Change detection
    needs: [base_ref_selection, image_setup]
    uses: ./.github/workflows/reusable_change_detection.yml
    with:
      base_ref: ${{ needs.base_ref_selection.outputs.base_ref }}
      image: ${{ needs.image_setup.outputs.image }}
    secrets:
      ecr-password: ${{ secrets.ECR_PASSWORD }}

  rust:
    name: Rust ecosystem
    if: ${{ fromJSON(needs.change_detection.outputs.cargo_pkgs) }}
    needs: [change_detection, image_setup]
    uses: ./.github/workflows/reusable_rust_ecosystem.yml
    with:
      image: ${{ needs.image_setup.outputs.image }}
      pkgs_arg: ${{ needs.change_detection.outputs.cargo_pkgs_args }}
      deploy: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      ecr-password: ${{ secrets.ECR_PASSWORD }}
      docs-deploy-key: ${{ secrets.DOCS_DEPLOY_KEY }}

  node:
    name: Node ecosystem
    if: ${{ fromJSON(needs.change_detection.outputs.npm_pkgs) }}
    needs: [change_detection, image_setup]
    uses: ./.github/workflows/reusable_node_ecosystem.yml
    with:
      image: ${{ needs.image_setup.outputs.image }}
      deploy: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      ecr-password: ${{ secrets.ECR_PASSWORD }}
      analytics-deploy-key: ${{ secrets.ANALYTICS_DEPLOY_KEY }}
      editor-deploy-key: ${{ secrets.EDITOR_DEPLOY_KEY }}

  book:
    name: Book
    needs: [image_setup, change_detection]
    if: ${{ fromJSON(needs.change_detection.outputs.docs) }}
    uses: ./.github/workflows/reusable_book.yml
    with:
      image: ${{ needs.image_setup.outputs.image }}
      deploy: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      ecr-password: ${{ secrets.ECR_PASSWORD }}
      deploy-key: ${{ secrets.BOOK_DEPLOY_KEY }}
