name: CI - Book

on:
  push:
    paths:
      - "doc/**"
      - ".github/workflows/ci_book.yml"
    branches:
      - main

jobs:
  build_book:
    name: Building book
    runs-on: [self-hosted, linux, base, build]
    steps:
      - uses: actions/checkout@v2

      - name: Build book
        run: make book

      - name: Upload book
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: ./target/book
          retention-days: 5

  deploy_book:
    name: Deploying book
    needs: [build_book]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: book
          path: ./book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.BOOK_DEPLOY_KEY }}
          external_repository: legion-labs/book.legionengine.com
          publish_branch: main
          publish_dir: ./book
          force_orphan: true
          cname: book.legionengine.com
